// src/lib/components/Footer.svelte
<script lang="ts">
	const socialLinks = [
		{
			label: 'GitHub',
			href: 'https://github.com/uongsuadaubung',
			icon: `<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>`
		},
		{
			label: 'Email',
			href: 'mailto:contact@uongsuadaubung.github.io',
			icon: `<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/></svg>`
		}
	];
</script>

<footer class="footer">
	<div class="container footer-inner">
		<div class="copyright-wrap">
			<p class="copyright">
				&copy; {new Date().getFullYear()} <span class="gradient-text">uongsuadaubung</span>. All rights reserved.
			</p>
			<p class="tech-stack">
				Designed & Built with <a href="https://kit.svelte.dev" target="_blank" rel="noopener noreferrer" class="svelte-link">SvelteKit</a>
			</p>
		</div>
		<div class="social-links">
			{#each socialLinks as link}
				<a href={link.href} target="_blank" rel="noopener noreferrer" aria-label={link.label} class="social-link">
					{@html link.icon}
				</a>
			{/each}
		</div>
	</div>
</footer>

<style lang="scss">
	.footer {
		border-top: 1px solid var(--border-subtle);
		padding: var(--space-8) 0;
		margin-top: auto;
	}

	.footer-inner {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: var(--space-4);
		flex-wrap: wrap;

		@media (max-width: 480px) {
			flex-direction: column;
			text-align: center;
		}
	}

	.copyright-wrap {
		display: flex;
		flex-direction: column;
		gap: var(--space-1);

		@media (max-width: 480px) {
			align-items: center;
		}
	}

	.copyright {
		font-size: 0.875rem;
		color: var(--text-primary);
		font-weight: 500;
	}

	.tech-stack {
		font-size: 0.8rem;
		color: var(--text-muted);

		.svelte-link {
			color: var(--text-secondary);
			text-decoration: none;
			position: relative;
			transition: color var(--transition-fast);

			&::after {
				content: '';
				position: absolute;
				bottom: -1px;
				left: 0;
				width: 100%;
				height: 1px;
				background-color: var(--border);
				transition: background-color var(--transition-fast);
			}

			&:hover {
				color: var(--accent-1);
				&::after {
					background-color: var(--accent-1);
				}
			}
		}
	}

	.gradient-text {
		background: var(--accent-gradient);
		-webkit-background-clip: text;
		-webkit-text-fill-color: transparent;
		background-clip: text;
		font-weight: 600;
	}

	.social-links {
		display: flex;
		align-items: center;
		gap: var(--space-2);
	}

	.social-link {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 36px;
		height: 36px;
		border-radius: var(--radius-full);
		color: var(--text-muted);
		border: 1px solid var(--border);
		background: var(--bg-elevated);
		transition:
			color var(--transition-fast),
			border-color var(--transition-fast),
			transform var(--transition-fast),
			background var(--transition-fast);

		&:hover {
			color: var(--accent-1);
			border-color: var(--accent-1);
			background: var(--tag-bg);
			transform: translateY(-2px);
		}
	}
</style>

// src/lib/components/Footer.tsx
import { For } from 'solid-js';
import './Footer.scss';

export default function Footer() {
	const socialLinks = [
		{
			label: 'GitHub',
			href: 'https://github.com/uongsuadaubung',
			icon: (
				<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
					<path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
				</svg>
			)
		},
		{
			label: 'Email',
			href: 'mailto:contact@uongsuadaubung.github.io',
			icon: (
				<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
					<path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/>
					<polyline points="22,6 12,13 2,6"/>
				</svg>
			)
		}
	];

	return (
		<footer class="footer">
			<div class="container footer-inner">
				<div class="copyright-wrap">
					<p class="copyright">
						&copy; {new Date().getFullYear()} <span class="gradient-text">uongsuadaubung</span>. All rights reserved.
					</p>
					<p class="tech-stack">
						Designed & Built with <a href="https://solidjs.com" target="_blank" rel="noopener noreferrer" class="solid-link">Solid JS + Vite</a>
					</p>
				</div>
				<div class="social-links">
					<For each={socialLinks}>
						{(link) => (
							<a href={link.href} target="_blank" rel="noopener noreferrer" aria-label={link.label} class="social-link">
								{link.icon}
							</a>
						)}
					</For>
				</div>
			</div>
		</footer>
	);
}
